= Documenting APIs with Swagger and AsciiDoc
:version-label!:

The document explains how to use the Swagger specification and the AsciiDoc markup language to generate reference
documentation for your RESTful APIs.

== Process overview

[plantuml, ./diagram, png]
.Generating documentation
....
@startuml

skinparam sequence {
  ActorBorderColor #0061a0
  ArrowColor #0061a0
  ParticipantBackgroundColor White
  ParticipantBorderColor #0061a0
}

actor Developer
participant "API Code" as API
participant "Swagger spec" as Swag
participant "AsciiDoc" as Adoc
participant "HTML/PDF" as Html

Developer -> API: Add Swagger annotations
alt Buiid time
    API -> Swag: Swagger plugin
else Run time
    API -> Swag: Springfox
end
Swag -> Adoc: Swagger2markup
Adoc -> Html: Asciidoctor

@enduml
....

== Generating a Swagger spec

https://swagger.io/[Swagger] is an open source framework backed by a large ecosystem of tools that helps developers
design, build, document, and consume RESTful Web services. At its heart is the
https://swagger.io/specification/v2/[Swagger Specification] which is used to describe a RESTful API in JSON or YAML format. 

The Swagger spec became the https://swagger.io/specification/[OpenApi Specification] in version 3.0. The examples shown
here use Swagger 2.0, since the tools we are using to generate the documentation have not yet caught up with the 3.0 standard.

You can choose to generate a Swagger specification from your API at either build time or run time.

=== Design first or code first?

Swagger can take either a design-first or code-first approach to API development. 

The design-first approach involves writing a Swagger or OpenAPI specification in JSON or YAML, circulating the
specification to stakeholders for approval, and generating code from the specification. In this scenario, the API
specification is the single source of truth for the API.

Code-first means that developers write the APIs using an appropriate RESTful coding framework, such as JAX-RS or Spring
MVC, and add Swagger annotations to the code during the development process. A Swagger specification is then generated
from the code either at build time or at run time. In this case, the code is the single source of truth.

This document deals with the code-first approach.

=== Swagger annotations

You add https://github.com/swagger-api/swagger-core/wiki/annotations-1.5.x[Swagger annotations] to your API code to ensure
that a Swagger spec is generated at run or build time. 

You declare the dependency on the Swagger Annotations library in the `build.gradle` in the project's API server module
as follows:

.Swagger Annotations dependency in build.gradle
[source,groovy]
----
dependencies {

  compile group: 'io.swagger', name: 'swagger-annotations', version: '1.5.17'

}
----

And then you add Swagger annotations to the resource classes, for JAX-RS projects, or to the controller classes in Spring
MVC. For example:

.Annotating a controller class
[source,java]
----
@Controller
@RequestMapping(value = "/pets", produces = "applicationjson")
@Api(value = "/pets", tags = "Pets", description = "Operations about pets")
public class PetController {

@RequestMapping(method = POST)
  @ApiOperation(value = "Add a new pet to the store")
  @ApiResponses(value = {@ApiResponse(code = 405, message = "Invalid input")})
  public ResponseEntity<String> addPet(
          @ApiParam(value = "Pet object that needs to be added to the store", required = true) @RequestBody Pet pet) {
    petData.add(pet);
    return Responses.ok("SUCCESS");
  }
}
----

Here are some of the most useful Swagger annotations:

[cols=",,",options="header",]
|===
|Annotation |Description |Attributes
|`@Api` |Marks the class as a Swagger resource.  a|
`tags` – Groups all the APIs in this class under a particular heading in the documentation

`description` – Adds a further description for this group of APIs

|`@ApiOperation` |Used to document an individual API, usually a unique combination of HTTP method and resource path a|
`value` – The name of the API. Appears as a section title in the generated documentation. For example "Get widget". Does
not end with a full stop (period).

`notes` – A more detailed description of what the API does, written as one or more sentences. For example, "Returns the
widget specified by the widgetUid parameter." 

`nickname` – Often required where the API method name is not unique across the project. For example, some projects use
the method names get, create, and update in every resource class. For example, "getWidget"

`response` – Where the response object cannot be inferred from the response statement in the code, you may need to use
this annotation to set the name of the response class. 

`code` – The HTTP response code that is returned when this API is called successfully. Defaults to 200, so you need to
set this for APIs that return 201, 202, and 204. Alternatively, you can set this in the @ApiResponse annotation.

|@ApiParam |Used to document parameters that can be sent when the API is called. a|
`value` – A description of the parameter that appears in the generated documentation.

`required` – A boolean showing whether the parameter is required. Defaults to false.

`allowableValues` – A comma-separated list of allowable values.

|`@ApiResponses` |Use this annotation where the response to a successful API call cannot be inferred from the code.
|None. Contains a list of `@ApiResponse` annotations.
|`@ApiResponse` |Defines an API response a|
`code` – The HTTP response code that is returned when this API is called successfully.

`message` – The message that accompanies the HTTP response, for example 'No content'.

`response` – The name of the response class.

|===

Where an API consumes a JSON object in the body of a request or produces JSON in the response, the model of the JSON
object is included in the generated `swagger.json`. You can add documentation to the model classes using the `@ApiModel`
and  `@ApiModelProperty` annotations. For example:

.Annotating a model class
[source,groovy]
----
class CredentialsModel {
  @ApiModelProperty(required = true) String username
  @ApiModelProperty(required = true) String password
}
----

See the https://github.com/swagger-api/swagger-core/wiki/annotations-1.5.x[Swagger Annotations documentation] for more details.

=== Generating Swagger at Build Time

The https://github.com/gigaSproule/swagger-gradle-plugin[Swagger Gradle Plugin] allows you to  generate a `swagger.json` 
file at build time.

NOTE: If you are using Maven as your build tool, you can use the https://github.com/kongchen/swagger-maven-plugin[Swagger Maven Plugin].

The dependency on this plugin and its configuration is declared in the `build.gradle` for each project's API server module.

.Swagger Gradle Plugin config in build.gradle
[source,groovy]
----
plugins {
    id 'com.benjaminsproule.swagger'
    version '1.0.4'
}

swagger {
    apiSource {
        springmvc = false
        locations = ['com.acme.widget.api.resources']
        schemes = ['http', 'https']
        host = '{{host}}'
        basePath = '/api'

        info {
            title = 'Widget API'
            version = 'v1'
            description = 'This is the API for the Widget service.'
            termsOfService = 'http://www.example.com/termsOfService'
            contact {
                email = 'engineering@acme.com'
                name = 'Widget'
                url = 'http://www.widgetinc.com/'
            }
        }
        swaggerDirectory = "${project(':widget-docs').buildDir}/swagger"
    }
}

generateSwaggerDocumentation.dependsOn(compileGroovy)
----

The `swagger.json` is generated by the `generateSwaggerDocumentation` Gradle task and is written to a `swagger` folder
under the docs module's `build` directory.

=== Generating Swagger at Runtime

You can also generate a `swagger.json` file at run time by executing a test against a running API server using one of the
following:

* http://springfox.github.io/springfox/[Springfox]
* https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5[Swagger Core with Jersey 2.0]

== Converting Swagger to AsciiDoc

Once you have generated the Swagger specification you can use the Swagger2markup library to convert it to AsciiDoc.

=== About AsciiDoc

http://asciidoc.org/[AsciiDoc] is an easy-to-use, lightweight markup language that is well supported by a wide range of
open source tools. It is similar to Markdown but is sophisticated enough to support many of the book-authoring features
provided by more complicated specifications such as DocBook and DITA. We use parts of the
https://asciidoctor.org/[Asciidoctor] tool chain to produce HTML and PDF from AsciiDoc source files.

=== Swagger2markup

The Swagger to AsciiDoc conversion is handled by the
https://github.com/Swagger2Markup/swagger2markup-gradle-plugin[Swagger2markup Gradle plugin], which is declared in the 
`build.gradle` of the project `docs` module.

NOTE: See the https://github.com/Swagger2Markup/swagger2markup-maven-plugin[Swagger2markup Maven plugin] if you are using
Maven.

.Configuring the Swagger2markup Gradle plugin
[source,groovy]
----
buildscript {

    dependencies {
        classpath "io.github.swagger2markup:swagger2markup-gradle-plugin:1.3.3"
        classpath "io.github.swagger2markup:swagger2markup-import-files-ext:1.3.3"
    }
}

...

ext {
    swaggerDir = file("${project.buildDir}/swagger")
    asciiDocOutputDir = file("${buildDir}/asciidoc/generated")
}

...

convertSwagger2markup {
    dependsOn(':mm-api-server:generateSwaggerDocumentation')
    swaggerInput "${swaggerDir}/swagger.json"
    outputDir asciiDocOutputDir
    config = [
        'swagger2markup.pathsGroupedBy': 'TAGS',
        'swagger2markup.extensions.dynamicPaths.contentPath': file('src/asciidoc/extensions/paths').absolutePath
    ]
}
----

The dependency on `swagger2markup-import-files-ext` and the `swagger2markup.extensions.dynamicPaths.contentPath`
configuration relate to how sample requests and responses are included in the generated documentation.

To convert the Swagger to AsciiDoc, run:

`./gradlew convertSwagger2markup`

=== Including sample requests and responses

It is good practice to include a sample request and response in the documentation for each your your APIs.

You can use the Swagger2markup http://swagger2markup.github.io/swagger2markup/1.3.1/#extension_import_files[Dynamic file import extension] 
and the http://swagger2markup.github.io/swagger2markup/1.3.1/#_pathsdocumentextension[PathsDocumentExtension] point to
import sample requests and responses into the generated API documentation.

You add the samples as follows:

. Ensure that the `swagger2markup.extensions.dynamicPaths.contentPath` property is set in the docs module's `build.gradle`.
  Typically this is: 

  src/asciidoc/extensions/paths

. Create a directory under the content path and name it the same as the API method name (if unique) or the `ApiOperation` nickname.
. In the new directory, create an AsciiDoc file called `operation-end-sample`.
. Call the API either by running an acceptance test or using cURL or Postman.
. Copy the output into the `operation-end-sample` file.

== Generating HTML and PDF

Once you have an AsciiDoc version of your API reference, you can combine it with other manually-maintained AsciiDoc
documentation, such as an introductory chapter or 'error codes' section, and generate the final output as HTML or PDF.

To do this, you use the https://github.com/asciidoctor/asciidoctor-gradle-plugin[Asciidoctor Gradle plugin]. Once again,
you declare the dependency in the docs module's build.gradle:

.Configuring the AsciiDoctor Gradle plugin
[source, groovy]
----
plugins {
    id 'org.asciidoctor.jvm.convert' version '3.1.0'
    id 'org.asciidoctor.jvm.pdf' version '3.1.0'
}

repositories {
    maven {
        url "https://repo.spring.io/release"
    }
    mavenCentral()
}

configurations {
    asciidoctorExt
}

dependencies {
    asciidoctorExt 'io.spring.asciidoctor:spring-asciidoctor-extensions-block-switch:0.4.1.RELEASE'
}

...

ext {
    asciiDocOutputDir = file("${buildDir}/asciidoc/generated")
    docBuildDir = file("${project.buildDir}/doc")
}

...

asciidoctor {
    configurations 'asciidoctorExt'
    sourceDir = file("src/asciidoc/")
    baseDirFollowsSourceFile()
    sources {
        include 'widget-apiguide.adoc'
    }
    outputOptions{
        backends = ['html5', 'pdf']
        separateOutputDirs = false
    }
    resources {
        from(sourceDir) {
            include 'images/**'
        }
        from(sourceDir) {
            include 'assets/js/**'
        }
    }

    outputDir docBuildDir
    backends = ['html5', 'pdf']
    attributes = [
        'doctype': 'book',
        'toc': 'left',
        'toclevels': '3',
        'source-highlighter': 'prettify',
        'revnumber': version,
        'docinfo': 'shared',
        'pdf-stylesdir': 'theme',
        'pdf-style': 'acme',
        'generated': asciiDocOutputDir
    ]
}
----

You generate the HTML and PDF by running the `asciidoctor` Gradle task. 

The Asciidoctor plugin depends on two other libraries:

* https://github.com/asciidoctor/asciidoctorj-pdf[AsciidoctorJPDF] is used for PDF generation
* https://github.com/spring-io/spring-asciidoctor-extensions[Spring Asciidoctor Extensions] post-processes Asciidoctor’s HTML output to collapse multiple code blocks into one that provides side-by-side code samples. The extensions are stored in the https://repo.spring.io/release[repo.spring.io] Artifactory repository, which is included in the repositories section of the build.gradle.

=== Including side by side code samples

Instead of displaying each sample request and response one below the other, as is the default, it can look good to render
them in a side-by-side tabbed view in the generated HTML.

For this you can use the block switch extension in the https://github.com/spring-io/spring-asciidoctor-extensions[Spring Asciidoctor Extensions] library.

Add the following dependency to your `build.gradle`:

[source,groovy]
----
configurations {
    asciidoctorExt
}

dependencies {
     asciidoctorExt 'io.spring.asciidoctor:spring-asciidoctor-extensions-block-switch:0.4.1.RELEASE'
}
----

You also need to add a `role` attribute to each of the source code blocks.
There must be one 'primary' role and at least one 'secondary' role.

So this markup ...

....
.Adding dependencies
====

[source,groovy,role="primary"]

.Gradle
----
implementation 'com.acme.widget.client:2.1.1'
----

[source,xml,role="secondary"]

.Maven
----
<dependency>
  <groupId>com.acme.widget.client</groupId>
  <artifactId>entertainment-client</artifactId>
  <version>2.1.1</version>
</dependency>
----
====
....

&#8230; is rendered like this:

.Adding dependencies
====

[source,groovy,role="primary"]

.Gradle

----
implementation 'com.acme.widget.client:2.1.1'
----

[source,xml,role="secondary"]

.Maven
----
<dependency>
  <groupId>com.acme.widget.client</groupId>
  <artifactId>entertainment-client</artifactId>
  <version>2.1.1</version>
</dependency>
----
====

=== Styling and themes

You use a https://asciidoctor.org/docs/user-manual/#docinfo-file[docinfo] file to override Asciidoctor's default CSS styling for HTML output.

For PDF output you use the https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc[theming] system.
These two lines in the Asciidoctor configuration in the `build.gradle` govern the themes used:

.Theming configuration
----
'pdf-stylesdir' : 'theme',
'pdf-style' : 'my_theme',
----

=== Including an expandable TOC

The default HTML output displays the table of contents as a simple list in the left-hand navigation frame.
You can use the https://tscanlin.github.io/tocbot/[Tocbot] JavaScript library to render an expandable TOC.
